### ISSUE TITLE
Cannot install, no module named Cython

### ISSUE THREAD

**Issue by paul-sud** [pyranges/bamread#2]
Hello,

I tried to install `bamread` via `pip` `20.3.3` and Python `3.7.4` but got the following error:

```
Collecting bamread==0.0.5
  Using cached bamread-0.0.5.tar.gz (109 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/paul/gitclones/chipseq-visualization/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0b/xvv26_mx5fv8sxp90csjrcm00000gp/T/pip-install-u8klatml/bamread_37c49647db44430d9b00730baf40e458/setup.py'"'"'; __file__='"'"'/private/var/folders/0b/xvv26_mx5fv8sxp90csjrcm00000gp/T/pip-install-u8klatml/bamread_37c49647db44430d9b00730baf40e458/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/0b/xvv26_mx5fv8sxp90csjrcm00000gp/T/pip-pip-egg-info-0ilv3x53
         cwd: /private/var/folders/0b/xvv26_mx5fv8sxp90csjrcm00000gp/T/pip-install-u8klatml/bamread_37c49647db44430d9b00730baf40e458/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0b/xvv26_mx5fv8sxp90csjrcm00000gp/T/pip-install-u8klatml/bamread_37c49647db44430d9b00730baf40e458/setup.py", line 7, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Seems like this might be a fix: https://luminousmen.com/post/resolve-cython-and-numpy-dependencies . It looks like `bamread`'s setup.py requires importing Cython to execute, but cython itself is a dependency.

Best,

Paul

**Comment by endrebak** [comment]
Thanks for the link! I looked into this earlier, but could not find an easy fix :)

**Comment by endrebak** [comment]
https://github.com/pyranges/sorted_nearest/pull/4
